### ISSUE TITLE
Make snippets saner: allow multiple snippets in one file

### ISSUE THREAD

**Issue by sn0wyfall** [bobthecow/sublime-sane-snippets#13]
Hey! So I was wondering if there could be an option to make sane snippets even saner. So normally with snippets, you need to make a separate file for each snippet you want to use, which can become rather tedious. Would it be possible to make sane snippets recognize multiple snippets in the sane-snippet file?

**Comment by bobthecow** [comment]
Possibly, but it would be complicated.

Since there aren't matching tags, like the XML used in (insane) snippets, you would have to come up with a delimiter to split the snippets. And you'd have to come up with syntax for escaping the delimiter, in case someone wanted a snippet with the delimiter in it.

See, for example, this sane snippet, which is used to generate sane snippets: https://github.com/bobthecow/sublime-sane-snippets/blob/master/SaneSnippet.sane-snippet

With a single frontmatter / metadata block, you can just assume that everything after that first `---` is content. If we allowed multiple snippets, it complicates things a bit :)

**Comment by sn0wyfall** [comment]
I see, thanks for the explanation. That does make sense. Personally I was wondering if it would be okay to have a really complicated delimiter – something random, such as `$&^(&#++&%&#(!^(` or something. I have no idea how feasible this is, as I don't know much about the languages this plugin is written in, but would that also be difficult? There would be no need to escape such a delimiter, as someone would (most likely!) never use `$&^(&#++&%&#(!^(`. However, as I said, I don't really know if this is easily feasible either, so if it's not I'll close this issue.

**Comment by lunixbochs** [comment]
You could allow setting a custom second delimiter in the frontmatter.

**Comment by bobthecow** [comment]
To be honest, this doesn't seem saner to me.

The point of sane snippets is that you don't have to think about delimiters, or escaping, or collisions or anything (at least for the snippet structure and metadata; there's not much sane snippets can do about the placeholder craziness).

I can't see a way for this to work which wouldn't compromise that, and I don't feel like editing fewer files is worth that tradeoff. I'm happy to be convince otherwise, though :)

**Comment by sn0wyfall** [comment]
You're insane!

Just kidding, it's okay. I'll try working around this!

**Comment by bobthecow** [comment]
:)
